name: Docs

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
    paths:
      - 'src/**.js'
      - 'src/**.jsx'
      - 'src/**.ts'
      - 'src/**.tsx'
      - 'src/**.json'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nju33'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - run: yarn
      - run: yarn gen-src-docs
      - run: |
          git config --local user.email "nju33@gmail.com"
          git config --local user.name "nju33"
          git commit -m "docs: update from docs workflow"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
